name: logic_sonic
description: "Logic With Sonic"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  video_player: ^2.9.5
  flutter_svg: ^2.1.0
  file_picker: ^10.1.9
  syncfusion_flutter_pdfviewer: ^29.2.8
  intl: ^0.20.2
  http: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/animals/
    - assets/laptop/
    - assets/svgs/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf


